# Path to epimodel-data directory
data_dir: data

# Replace with the actual channel (non-public)
foretold_channel: SECRET

### GLEAM

# data/sims subdirectory of gleamviz
gleamviz_sims_dir: /Users/jakey/GLEAMviz-data/sims
# Path to epimodel-data directory
data_dir: data

# Subsampling of imported data (see Pandas `df.resample`)
gleam_resample: 1D

### Extra data for web_export, relative to data_dir
web_export:
  john_hopkins: johns-hopkins.csv
  foretold: foretold.csv
  rates: rates.csv
  timezones: timezones.csv
  un_age_dist: various/age_dist_un.csv
  traces_v3: various/traces_v3.csv

### Generating GLEAM scenarios
# All combinations of groups and scenarios are created,
# unifying the attributes. Semantics:
# - param_beta_multiplier is applied to all beta (incl. exceptions)
# - param_beta_exceptions is list of [[days, vaue], [days, value], ...],
#   where value is eother a number, os region column name
# - param_beta is the global parameter setting
scenarios:
  - name: Irrelevant
    key: "IRRELEVANT"

groups:
  - group: "Default_Weak"
    name: Weak mitigation
    description: Mostly open borders; full opening of public places; no social distancing; little compliance with hygiene advice

  - group: "Default_Moderate"
    name: Moderate mitigation
    description: Some border closure; closure of schools; ban on public gatherings; partial social distancing

  - group: "Default_Strong"
    name: Strong mitigation
    description: Strong external and internal border closure; full closure of public places (including places of worship); social distancing outside and within homes

  - group: "Default_Recommended"
    name: Recommended mitigation
    description: Moderate measures + compulsory masks; contact tracing; social distancing at places of worship and within homes


# How to assign estimate different compartments
compartment_multipliers:
  Infectious: 1.0
  Exposed: 1.8

# Maximal fraction of population in a region that is in
# some compartment
compartments_max_fraction: 0.8

### Upload settings
gs_prefix: "gs://static-covid/static/"
gs_url_prefix: "https://storage.googleapis.com/static-covid/static/"

### Output directory for exported data
output_dir: out/

### List of exported regions code
export_regions:
  - G-SDT
  - G-PEW
  - G-ISB
  - G-GIL
  - G-KDU
  - G-SKT
  - G-LHE
  - G-LYP
  - G-DSK
  - G-MUX
  - G-DEA
  - G-BHV
  - G-RYK
  - G-PZH
  - G-UET
  - G-SUL
  - G-SKZ
  - G-KCF
  - G-MJD
  - G-DBA
  - G-PJG
  - G-TUK
  - G-GWD
  - G-DDU
  - G-KHI
  - G-WNS
  - G-HDD
  - PK
  - PK-AJK
  - PK-BA
  - PK-GB
  - PK-ICT
  - PK-KP
  - PK-PB
  - PK-SD

### these are used to match our non-state codes (e.g. AU) for John Hopkins database
### where they have it on state/province granularity
state_to_country:
  - AU
  - CN
  - CA

### Define extra regions that are composed of arbitrary other regions.
### Region info not specified here will either be aggregated from the
### specified children if possible or left blank.
### children can be a list or a dict. If a list, the forecasting model
### for each child will be weighted according to population. If a dict,
### the values specify additional weights that will be multiplied by
### population before being applied to the model traces.

custom_regions:
  PK-AJK:
    Name: 'Azad Jammu & Kashmir'
    Population: 4100000
    children:
      G-SDT: 0.02
      G-ISB: 0.08
      G-IXJ: 1
  PK-BA:
    Name: 'Balochistan'
    Population: 10728000
    children:
      G-DEA: 0.05
      G-PZH: 0.9
      G-UET: 1
      G-SUL: 0.8
      G-SKZ: 0.06
      G-MJD: 0.3
      G-DBA: 1
      G-PJG: 1
      G-TUK: 1
      G-GWD: 1
      G-DDU: 0.7
      G-KHI: 0.02
  PK-GB:
    Name: 'Gilgit-Baltistan'
    Population: 5400000
    children:
      G-CJL: 0.25
      G-GIL: 1
      G-KDU: 1
  PK-ICT:
    Name: 'Islamabad Capital Territory'
    Population: 15300000
    children:
      G-ISB: 0.21
  PK-KP:
    Name: 'Khyber Pakhtunkhwa'
    Population: 31900000
    children:
      G-CJL: 0.75
      G-SDT: 0.98
      G-PEW: 1
      G-ISB: 0.15
      G-DSK: 0.6
      G-PZH: 0.1
  PK-PB:
    Name: 'Punjab'
    Population: 96200000
    children:
      G-ISB: 0.56
      G-SKT: 1
      G-LHE: 1
      G-LYP: 1
      G-DSK: 0.4
      G-MUX: 1
      G-DEA: 0.95
      G-BHV: 1
      G-RYK: 1
  PK-SD:
    Name: 'Sindh'
    Population: 45900000
    children:
      G-SUL: 0.2
      G-SKZ: 0.94
      G-KCF: 1
      G-MJD: 0.7
      G-DDU: 0.3
      G-KHI: 0.98
      G-WNS: 1
      G-HDD: 1
